version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Starting Deploy job
      - aws --version
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - ACCOUNT=${account}
      - TELEGRAM_TOKEN=${telegram_token}
      - TELEGRAM_CHAT_ID=${telegram_chat_id}
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ACCOUNT.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building image...
      - docker build --build-arg TELEGRAM_TOKEN=$TELEGRAM_TOKEN --build-arg TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID --platform=linux/amd64 -t promiedos .
      - echo Tagging image...
      - docker tag promiedos $ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/promiedos:latest
      - echo Pushing image...
      - docker push $ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/promiedos:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Updating lambda function...
      - aws lambda update-function-code --function-name promiedos --image-uri $ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/promiedos:latest --publish
